### ISSUE TITLE
Home Page Search Box Element ID's Not Unique 

### ISSUE THREAD

**Issue by ahubble** [UCSCLibrary/SiteImprove#11]
**Issue**: The ID used for an element on the page is also used for another element on the page: #simple element ID not unique  10 errors.

See [Siteimprove page report](https://my2.siteimprove.com/Inspector/624596/Accessibility/Page?pageId=15773084806&impmd=38C0679FF2A7ED22BA80423C710AC71F#/Criterion/1.3.1/Check/33) for details

![Screen Shot 2020-04-22 at 1 29 02 PM](https://user-images.githubusercontent.com/21367942/80030815-956e7f00-849d-11ea-937e-65498151c1e7.png)
![Screen Shot 2020-04-22 at 1 29 24 PM](https://user-images.githubusercontent.com/21367942/80030827-99020600-849d-11ea-8526-fdee924f114d.png)

**Comment by rschwab** [comment]
The fix for this is staged in git, ready to go when the online scope has been approved.
