### ISSUE TITLE
LibApps Search box in top menu: Label is not connected to a form control

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/SiteImprove#39]
Problem appears to be with the upper right site search box in the top menu in LibApps (LibGuides, LibCal, LibAnswers)

**Description of this issue:**
The label for the form control is not explicitly connected to anything, since it refers to an element ID that does not exist on the page.
**How to fix it:**
When using the ‘label’ it must be explicitly connected to a form control, such as an input field, a text field, a combo box, a radio button or a check box. Using standards like this helps user agent render content properly to the user.

<img width="1018" alt="Screen Shot 2020-05-15 at 9 43 11 AM" src="https://user-images.githubusercontent.com/6412857/82075127-a1aabe00-9690-11ea-90e3-096bd7b14897.png">

<img width="1024" alt="Screen Shot 2020-05-15 at 9 43 20 AM" src="https://user-images.githubusercontent.com/6412857/82075129-a53e4500-9690-11ea-8fec-d5df6cd6558a.png">

**Comment by rschwab** [comment]
Resolved by changing the for value to "edit-keys":
`<label class="element-invisible" for="edit-keys">Search </label>`
`<input title="Enter the terms you wish to search for." type="text" id="edit-keys" name="keys" value="" size="40" maxlength="128" class="form-text" />`
