### ISSUE TITLE
Library Homepage Select Box Needs Description

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/SiteImprove#4]
Select Box appears instead of tabs for smaller screens. 

**Description of this issue:**
Drop down menus (select boxes or role="listbox") should always have a description that is explicitly associated with the field to make sure that users of assistive technologies will also know what the field is for.

**How to fix it:**
If the drop down menu (select box or role="listbox") has a visible description indicating the purpose of the menu, this description should be explicitly associated to the input drop down menu either as a HTML label or using the WAI-ARIA attribute 'aria-labelledby'.

If it is not possible to add a visible description, create an invisible label using the WAI-ARIA attribute 'aria-label'.

<img width="699" alt="Screen Shot 2020-04-14 at 9 59 38 AM" src="https://user-images.githubusercontent.com/6412857/79252706-e5fb3200-7e36-11ea-98bd-704316c7054c.png">

**Comment by rschwab** [comment]
This one is fixed in the git staging, will be rolled out with the new online scope code.
